global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yaml

scrape_configs:
  - job_name: multichain-indexer
    static_configs:
      - targets: ["indexer:8080"]
    metrics_path: /metrics
    scrape_interval: 10s
