{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "multichain-indexer.fullname" . }}
  labels:
    {{- include "multichain-indexer.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "multichain-indexer.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.healthCheck.port }}
          protocol: TCP
        {{- if and .Values.service.adminPort (gt (int .Values.service.adminPort) 0) }}
        - port: {{ .Values.service.adminPort }}
          protocol: TCP
        {{- end }}
  egress:
    - {}
{{- end }}
