{{- if and .Values.autoscaling.enabled (gt (int .Values.autoscaling.minReplicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "multichain-indexer.fullname" . }}
  labels:
    {{- include "multichain-indexer.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "multichain-indexer.selectorLabels" . | nindent 6 }}
{{- end }}
