{{- if and .Values.secret.create (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multichain-indexer.fullname" . }}
  labels:
    {{- include "multichain-indexer.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_URL: {{ .Values.secret.dbUrl | quote }}
  {{- if .Values.secret.metricsAuthUser }}
  METRICS_AUTH_USER: {{ .Values.secret.metricsAuthUser | quote }}
  {{- end }}
  {{- if .Values.secret.metricsAuthPass }}
  METRICS_AUTH_PASS: {{ .Values.secret.metricsAuthPass | quote }}
  {{- end }}
{{- end }}
