apiVersion: v1
kind: Service
metadata:
  name: {{ include "multichain-indexer.fullname" . }}
  labels:
    {{- include "multichain-indexer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
    {{- if and .Values.service.adminPort (gt (int .Values.service.adminPort) 0) }}
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
    {{- end }}
  selector:
    {{- include "multichain-indexer.selectorLabels" . | nindent 4 }}
